#!/usr/bin/env bash
# Configure new nginx server to have a custom header
sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html
sudo mkdir -p /var/www/error

sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /var/www/error
sudo chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# echo "11i\add_header X-Served-By $hostname;" >> /etc/nginx/nginx.conf
# sudo service nginx restart

server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
