#!/usr/bin/env bash
# Process and PID file
/var/run/myscript.pid < echo "$$"
i=0
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
while [ $i -lt 10 ]
do
    echo "To infinity and beyond"
done
rm /var/run/myscript.pid
